### PR TITLE
PHP 8.4 support (Implicitly marking parameter $request as nullable is deprecated, the explicit nullable type must be used instead)

### PR DESCRIPTION
**Pull request by puzzledmonkey**
This PR adds support for PHP8.4, which has changed how we need to define nullable function parameters - they must be marked explicitly now (i.e. `Service|null $service = null` instead of just `Service $service = null`)

I've tried to minimise the code changes and stick with the code style (i.e. `Service|null` instead of `?Service`) of the original files but please let me know if there is anything you would like to to fix/revisit/explain more.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jubeki** [comment]
@puzzledmonkey Support for Union Types was only added in PHP 8.0:
See https://www.php.net/manual/en/language.types.declarations.php

This library supports PHP >= 7.2.5.

To support PHP 8.4 and keep backwards compatibility you would need the `?`, which was added in PHP 7.1.

For the maintainers:
The explicit nullable type (`?`) is fully backwards compatible and contain no breaking changes.
See the following article: https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated#change

The explicit declaration is compatible with PHP 7.1 and later, even if you extend the class.

You can also take a look at the following snippet at [PHP Playground at php-play.dev](https://php-play.dev/?c=DwfgDgFmBQ0MYBsCGBnFACACkgTgUwDsAXAYWTXQG9p1awBXAIwQEs50AzeguIlgewLoieFCJwAKEGJwsCAc3QASAG5IE9POgC86AvQQIAlFQC%2B0c9AD0V9ABUILDIlQYn6OPwC2YJH2ZaSBziWAASmOgA7AB0AIwANOiMeHBI9ChaLEToANZ4eGAYRBBa%2BobCAJ5gmT6scFkIFdHw5BgAykxkruh4AB4iBAAmGNj4xF0U1LTTDMxsnNy8AkIiYniSMnKKquqaOnoGxmYWsDb2js6t6O6ePn4sAehBIZjhUXGJyanpmdl5BUUSgdykQqlo%2BmA6g0mi1uh1GBMUAAmKg0OhMOoLHh8QTCUTiKSbBTKNQaPAmSjmSxnBw3K7uAj8bK3Xz%2BBDglSEJJ4Dj8fBhCIADmiABZPik0hlhECWLU2FlgQhKtVrhh8F5%2BJzBs0XBR4YiAMw9fqEYZYXCEUhXKbTdCzTFcbHLPFrDZEWTEnZkilU062WmXboMpkebysh7snqcoTJXn815C0Xi75S4o1SHy7JlJWglXudWavDa2F6zqtEXGgZm0aWxGo212jHzR1LXGrAlE7akva6ADkvV7PpOQA&v=8.3&f=html)

```php
<?php

class ParentClass {
   public function tester(?string $value = null) {}
}

// This class is compatible after PHP 7.1, because it keeps the null type implicitly.
class SubClass extends ParentClass {
     public function tester(string $value = null) {}
}

// This class is compatible after PHP 7.1, because it keeps the null type explicitly.
class SubClass2 {
   public function tester(?string $value) {}
}

// Fatal Error: This class is not compatible with the parent class even before PHP 8.4,
// because the implicit null type is removed from the declaration.
class SubClass3 extends ParentClass {
     public function tester(string $value) {}
}

// Fatal Error: This class is not compatible with the parent class even before PHP 8.4,
// because the implicit null type is removed from the declaration.
class SubClass4 extends ParentClass {
     public function tester(string $value = 'x') {}
}
```

**Comment by puzzledmonkey** [comment]
Sorry @Jubeki I didn't spot your PR for some reason (I did search!) so I'll close this one now.

**Comment by Jubeki** [comment]
@puzzledmonkey you can keep your PR open. My PR was closed, so it would be great if another PR is considered.

**Comment by puzzledmonkey** [comment]
This PR also now uses the backwards-compatible ? syntax rather than |null, and this should therefore mean this PR has no breaking changes at all, and just adds forwards-compatibility for PHP 8.4

**Comment by yenfryherrerafeliz** [comment]
Hi @puzzledmonkey, thanks for your contribution. I will be closing this PR in favor of [this](https://github.com/aws/aws-sdk-php/pull/2995) one which was opened a bit earlier for addressing this. Please track any further updates there.

Thanks!

**Pull request closed without merging**
