### PR TITLE
Feature/generate shared examples

### PR DESCRIPTION
**Pull request by jeskew**
This PR merges in #706 and fixes a few merge conflicts.

/cc @mtdowling @chrisradek

### CODE REVIEW

**Comment by jeskew** [comment]
The test failure is unrelated and is addressed in #832

**Comment by mtdowling** [comment]
Is there any way we can add tests to the example builder?

Given that we represent date/time values as DateTime objects in responses, do you want to represent that somehow in a response? What about blob types in a response? If you do want to do that, then you'll need to walk the model at the same time as walking the example data.

**Comment by jeskew** [comment]
@mtdowling I updated the PR to walk the model and insert marker values for dates and blobs. This allows for better support of structures and maps, too.

**Comment by mtdowling** [comment]
:ship:

**Pull request merged**
