### PR TITLE
Fix deprecation notices

### LINKED ISSUE #2355: Deprecated function: Return type of Aws\ResultPaginator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
When using this package with PHP 8.1, the following notice appears:
```
Deprecated function: Return type of Aws\ResultPaginator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

**Version of AWS SDK for PHP?**
3.207.1

**Version of PHP (`php -v`)?**
8.1

**To Reproduce (observed behavior)**
The error appears when calling `Aws\AwsClient->getPaginator('ListObjects')`

**Expected behavior**
No deprecation notice.

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #2355.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dandrei** [comment]
Another deprecation notice FYI that is triggered at least by `requestSpotInstances`:

```
Array (
[type] => 8192 
[errMsg] => ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated
[errFile] => /srv/da/webapp/vendor/aws/aws-sdk-php/src/Api/Serializer/Ec2ParamBuilder.php 
[errLine] => 15
) 
```

**Comment by xmav** [comment]
looks like already covered in https://github.com/aws/aws-sdk-php/pull/2354

**Comment by SamRemis** [comment]
Agreed, but #2354 isn't currently backward compatible.  I'll leave this open for a bit in case that one can't be merged

**Comment by DieterHolvoet** [comment]
Seems like backwards compatibility is being worked on, I'll close this.

**Pull request closed without merging**
