### PR TITLE
Update major version of guzzle calculation

### PR DESCRIPTION
**Pull request by gmponos**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gmponos** [comment]
cc @Nyholm maybe you would also like to have a look here?

**Comment by Nyholm** [comment]
This will it work with beta1. Is that a problem? Should we add a conflict in composer.json? If so, when do we remove that?

Or many we don’t care since we define this to work with guzzle7. It will work with guzzle7.

**Comment by gmponos** [comment]
hm... maybe this should wait until the RC. 

IIRC versions with RC do not allow BC so things can not break after..

**Comment by gmponos** [comment]
not sure why the CI is not running.. but I think that now that guzzle has RC tagged this can be merged.

**Comment by gmponos** [comment]
Unfortunately phpstan build is failing. There is a PHPStan known issue with constant and `defined`. Should I add an `ignoreError` in the phpstan.neon ?

**Comment by Nyholm** [comment]
Yes please. It is a priority that this is fixed.

**Comment by Nyholm** [comment]
I made a [small PR](https://github.com/aws/aws-sdk-php/pull/2050) to show that master is red.

**Comment by gmponos** [comment]
The failing build is unrelated.

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
