### PR TITLE
chore: bump guzzle

### PR DESCRIPTION
**Pull request by stobrien89**
Description of changes:
Bumping Guzzle 6 & 7 to address [GHSA-cwmx-hcrq-mhc3](https://github.com/guzzle/guzzle/security/advisories/GHSA-cwmx-hcrq-mhc3)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by SamRemis — APPROVED** [review]

**Comment by SamRemis** [comment]
Should this have a changelog?

**Comment by GrahamCampbell** [comment]
This specific advisory does not affect the AWS SDK. It is related to cookies.

**Comment by GrahamCampbell** [comment]
One should also remember that bumping these versions does not mean people will get secure versions of Guzzle... composer may just resolve an older version of the aws sdk before you bumped the version, to enable installation of vulnerable versions of guzzle, which could be worse!

**Comment by stobrien89** [comment]
@GrahamCampbell I jumped the gun after receiving the notice I mentioned in my other comment.  We've discussed this and agree that this could potentially be worse and will be rolling back these changes.  Thanks again for pointing it out!

**Pull request merged**
