### PR TITLE
Add missing AccessDeniedException class referenced by the getUser fun…

### PR DESCRIPTION
**Pull request by adam-ut**
I ran into an issue when using the IamClient getUser function. It said that the AccessDeniedException class didn't exist. This commit adds the file, following the standards of the other AWS Exception classes.

### CODE REVIEW

**Comment by jeskew** [comment]
Do you have a more detailed error message? The only [modeled error responses for `GetUser`](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/Iam/Resources/iam-2010-05-08.php#L2982) are `NoSuchEntityException` and `ServiceFailureException`.

**Comment by adam-ut** [comment]
Here's the error message: Unable to find class file for class "Aws\Iam\Exception\AccessDeniedException"

Here's the stack trace:

* spl_autoload_call was called 
* class_exists was called from NamespaceExceptionFactory.php:74 
* Aws\Common\Exception\NamespaceExceptionFactory->fromResponse was called from ExceptionListener.php:55 
* Aws\Common\Exception\ExceptionListener->onRequestError was called 
* call_user_func was called from EventDispatcher.php:164 
* Symfony\Component\EventDispatcher\EventDispatcher->doDispatch was called from EventDispatcher.php:53 
* Symfony\Component\EventDispatcher\EventDispatcher->dispatch was called from Request.php:589 
* Guzzle\Http\Message\Request->processResponse was called from Request.php:378 
* Guzzle\Http\Message\Request->setState was called from EntityEnclosingRequest.php:49 
* Guzzle\Http\Message\EntityEnclosingRequest->setState was called from CurlMulti.php:303 
* Guzzle\Http\Curl\CurlMulti->processResponse was called from CurlMulti.php:257 
* Guzzle\Http\Curl\CurlMulti->processMessages was called from CurlMulti.php:240 
* Guzzle\Http\Curl\CurlMulti->executeHandles was called from CurlMulti.php:224 
* Guzzle\Http\Curl\CurlMulti->perform was called from CurlMulti.php:111 
* Guzzle\Http\Curl\CurlMulti->send was called from CurlMultiProxy.php:94 
* Guzzle\Http\Curl\CurlMultiProxy->send was called from Client.php:284 
* Guzzle\Http\Client->send was called from AbstractClient.php:256 
* Aws\Common\Client\AbstractClient->send was called from Client.php:136 
* Guzzle\Service\Client->execute was called from AbstractCommand.php:153 
* Guzzle\Service\Command\AbstractCommand->execute was called from AbstractCommand.php:189 
* Guzzle\Service\Command\AbstractCommand->getResult was called from Client.php:76 
* Guzzle\Service\Client->__call was called from AbstractClient.php:104 
* Aws\Common\Client\AbstractClient->__call was called from AwsConnector.class.php:123 
* Aws\Iam\IamClient->getUser was called from AwsConnector.class.php:123

**Comment by jeskew** [comment]
Each service has an exception class that is used by default if no concrete class exists for a given error. The line in the SDK at the top of the call stack is not attempting to instantiate a class, just asking whether that class exists:
```php
$className = class_exists($className) ? $className : $this->defaultException;
```

It looks like the error is being thrown in `spl_autoload_call`. Do you have an autoloader registered that throws exceptions or triggers errors? 

Many exceptions are not modeled, so even if this particular class is added, you will likely see this error again if its underlying cause is not addressed.

**Comment by adam-ut** [comment]
Yes, there are other spl_autoload_call functions being loaded in our framework which could be doing as you've outlined. I'll have a look around the code using the information you've provided.

Thank you!

**Comment by jeskew** [comment]
Cool. I'll close this PR for now, as the issue probably won't be solved by adding a new exception class. Please feel free to reopen if you have any questions or concerns.

**Pull request closed without merging**
