### PR TITLE
Adding a rejected promise handler to determineBucketRegionAsync

### PR DESCRIPTION
**Pull request by cjyclaire**
Addressing issue #1065 

Adding a rejected promise handler to `determineBucketRegionAsync` to surface exception immediately when making a `HEAD` bucket request.

cc:\ @mtdowling @xibz @jeskew

### CODE REVIEW

**Comment by jeskew** [comment]
You might want to add a test with an exception that *does* contain a response, as would be generated by the situation discussed in #1065. (An `x-amz-bucket-region` header would be present on a 4XX response, and no exception would be surfaced.)

**Comment by cjyclaire** [comment]
@jeskew Make sense! This test case is added in the latest commit.

**Comment by jcchavezs** [comment]
Will this be merged soon?

**Comment by mtdowling** [comment]
:shipit:

**Pull request merged**
