### PR TITLE
Prevents S3 CompleteMultipartUpload failures by retrying the request.

### PR DESCRIPTION
**Pull request by jeremeamia**
For your review @mtdowling

### CODE REVIEW

**Comment by mtdowling** [comment]
Looks good. Are the test failures related?

**Comment by jeremeamia** [comment]
Trying to figure those out. I did not have those earlier. :-/

**Comment by jeremeamia** [comment]
Ah, test state got me down. All better.

**Comment by mtdowling** [comment]
LGTM

**Comment by mtdowling** [comment]
Is this good to merge? Is there something else that needs to be done?

**Comment by jeremeamia** [comment]
It's good. Just forgot.

**Pull request merged**
