### PR TITLE
Support latest guzzle promises

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by SamRemis** [comment]
Hi Graham,
[We announced](https://github.com/aws/aws-sdk-php/discussions/2638) dropping support for versions below 7.2.5 in February which will be effective on August 15th, 2023.  Totally agree with you here.

**Comment by GrahamCampbell** [comment]
Excellent news. 🎉

**Comment by bmckay959** [comment]
I'm also running into the issue mention in #2681 

Is there a recommended fix in the meantime before August 15th?

**Comment by GrahamCampbell** [comment]
You need to upgrade to the very latest version of this SDK, which may result in other packages begin downgraded, but if you do that, the SDK will work properly.

**Pull request closed without merging**
