### PR TITLE
enhancement: update to crt signing config

### PR DESCRIPTION
**Pull request by stobrien89**
*Description of changes:*
Updates the CRT signing config's handling of the region option

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by yenfryherrerafeliz — APPROVED** [review]

**Review by GrahamCampbell — COMMENTED** [review]
Why have the the additional constraints on Guzzle been added?

**Comment by yakobe** [comment]
@stobrien89 could you let us know why the additional constraints on Guzzle were added on this PR? It now prevents us from updating the sdk.

**Comment by GTony** [comment]
The constraint was added with this PR, then the PR was reverted. Yet the constraint still remains for no apparent reason.

**Comment by GrahamCampbell** [comment]
Yep, because the PR was not "reverted", just the commit message says it was. The revert commit does not revert the version constraint, so was not a complete revert.

**Pull request merged**
