### PR TITLE
Add 502 & 504 error code for retry

### PR DESCRIPTION
**Pull request by cjyclaire**
Add retry logic for Http Error Code 502 & 504.

cc: @jeskew @mtdowling

### CODE REVIEW

**Comment by jeskew** [comment]
This is a simple change, but could you augment [the relevant test](https://github.com/aws/aws-sdk-php/blob/master/tests/RetryMiddlewareTest.php#L42)?

**Comment by cjyclaire** [comment]
Fixed. @jeskew

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by jeskew** [comment]
:ship: 🇮🇹

**Pull request merged**
