### PR TITLE
PR-01 - Nette Framework AWS SDK Extension

### PR DESCRIPTION
**Pull request by JakubKontra**
Hi,
could you please add our new AWS SDK Extension for Nette framework to related projects list?

Thanks!

### CODE REVIEW

**Comment by marekjalovec** [comment]
AWS SDK works fine with Nette FW without custom extension for DI container (I'm using it that way every day on one project), it's just one line to create a new AWS Client and this even forces you to checkout your key to the repository, which is not something you should do at all.

**Comment by paveljanda** [comment]
@marekjalovec What you wrote is completely against modern coding standards.

1, It is not necessary to create more instances of S3Client. (or other asw sdk clients)
2, Nette DIC takes care of singletons perfectly
3, Configuration parameters should stay in config (*.neon) files.
4, Nette Extensions are perfect way how to distribute these configurations / classes registration along other projects / teams.

You should use it, really. :)

**Comment by paveljanda** [comment]
@marekjalovec And what do you mean by "checkout your key to the repository, which is not something you should do at all"?

This is just an extension, config parameters stays in project. Or did you mean something else?

**Comment by marekjalovec** [comment]
@paveljanda I am not saying I create more clients, just the one singleton. but this extension encourages users to checkout aws credentials into config.neon file in the project repository. you should never have such stuff in your repo. ever.

**Comment by JakubKontra** [comment]
@marekjalovec I'm probably blind. I can't see problem there. You don't need put your credentials into config.neon. You can use for example config.local.neon / config.production.neon to specify it.

**Comment by paveljanda** [comment]
Where do store the secret cay?

The thing is, you should leave all configuration parameters (credentials etc) at one place. Nette Framework gives you the ability to use perfect `neon` format. So put it in there.

Another thing is being earnest and storing these data in for example `config.local.neon` only on your server..

**Comment by juniwalk** [comment]
@marekjalovec If you think that it forces you to commit your secret keys to git then you are using it wrong in the first place.

You are supposed to create separate `*.neon` file and fill params there and then include in in `config.neon` or in your bootstrap.php. You of course have to add it into `.gitignore` file. That is how you use it.

**Comment by marekjalovec** [comment]
You should maybe emphasize that in the docs, so people won't screw up :-)

**Comment by fprochazka** [comment]
Improving the documentation with the usage pattern is definitely a good idea.

The package may be simple, but isn't that an advantage really?
Imho even a single class deservers a package, if it makese sense. I see no problem with this.

I see no problem with the package.

**Comment by cjyclaire** [comment]
Thanks for the pull request (and conversation :) ). The intent is to list the AWS-provided projects there; I've updated the README to make that clearer. PR: #1006

**Comment by paveljanda** [comment]
It's pretty bad luck for Nette framework then. Also I don't see any advantage of aws taking care of these extensions (the symfony bundle requires aws/aws-sdk-php in version ^3.2.6, so it's not that aws provides support for latest versions of aws-sdk-php).

Anyway, thanks for the reply.

**Pull request closed without merging**
