### PR TITLE
Adjust float conversion according to PHP8.1 changes

### PR DESCRIPTION
**Pull request by Corepex**
*Description of changes:*
Added `intval()` to explicitly convert floats (returned from `pow()`) to integers.
This avoids several "deprecated errors" in php8.1 (and above)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stobrien89** [comment]
Hi @Corepex,

Thanks for the PR!  Looks good to me.  Would you mind adding a (enhancement) changelog entry for this?  Instructions can be found in the [contributing guide](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md).

**Review by stobrien89 — APPROVED** [review]

**Comment by Corepex** [comment]
> Hi @Corepex,
> 
> Thanks for the PR! Looks good to me. Would you mind adding a (enhancement) changelog entry for this? Instructions can be found in the [contributing guide](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md).

sure, i added `.changes/nextrelease/3.222.9`

Hope this is correct 👍

**Comment by stobrien89** [comment]
Hi @Corepex,

Thanks for getting that added.  The file will need to have a `.json` extension and is only guaranteed to go out in the release following the merge, so if you could re-name it to `float-conversion.json` or something similar, that would work.

**Comment by stobrien89** [comment]
Hi @Corepex,

Thanks for getting that added.  The file will need to have a `.json` extension and is only guaranteed to go out in the release following the merge, so if you could re-name it to `float-conversion.json` or something similar, that would work.

**Comment by Corepex** [comment]
> Hi @Corepex,
> 
> Thanks for getting that added. The file will need to have a `.json` extension and is only guaranteed to go out in the release following the merge, so if you could re-name it to `float-conversion.json` or something similar, that would work.

Hi @stobrien89, 

thank you for your patience. 
I have now renamed the file as suggested. Hope it is correct now :)

**Comment by SamRemis** [comment]
I think the problem here is that it's not in the nextrelease folder, so the auto changelog builder won't be able to pick it up properly.  The file should be .changes/nextrelease/enhancement-float-conversion.json.  

Sorry for the confusion

**Pull request merged**
