### PR TITLE
added functionality for chmod in S3 StreamWrapper

### PR DESCRIPTION
**Pull request by femans**
chmod works now too, which is very useful because there is no option yet to upload files through a frontend of a webapp to s3 and have them available for the end user, just using the streamwrapper. 
Well, that is what I needed it for.

### CODE REVIEW

**Comment by jeskew** [comment]
I like the idea of supporting `chmod` with the S3 StreamWrapper, but I'm not sure I agree with how you're mapping permissions. Why is this looking at the user permissions instead of global permissions? I would personally be surprised if calling `chmod('s3://bucket/key', 0700)` made an object world-readable.

**Comment by jeskew** [comment]
I'd prefer to have @mtdowling weigh in before proceeding.

**Comment by femans** [comment]
Hi Jeskey, honestly, I think you are right. I didn´t think about it too much because I used the mapping code of mkdir, which I assumed to be right. But is that then sound, or should this too be different? 
I wouldn´t mind improving the mapping and commit it.

**Comment by femans** [comment]
Ok I examined the code, and it appears indeed at least odd to me how the permissions are mapped, if not a minor security issue. I don´t know how I overlooked this to begin with, except lack of time. I only used chmod to set public-read files. I think this should be changed as well for mkdir.

My suggestion would be to map the following canned acl´s:
public-read: the third digit is 4 or 5
public-read-write: the third digit is 6 or 7
private: the rest

the rest don´t get mapped. The second digit is omitted. Its a little rudimentary, but I guess more accurate than allowing public-read for 7xx, and authenticated-read for 6xx.

I will write the code tomorrow-ish and submit another pull request.

**Comment by femans** [comment]
So if the suggested mapping is agreed, I will build it in this branch.

**Comment by femans** [comment]
I added the alternative mapping function for chmod, next to the one for mkdir. It isn´t very clean to have two different mapping functions for no apparent reason, but at least mkdir functionality is not compromised.

**Comment by mtdowling** [comment]
Octal permissions don't cleanly map to Amazon S3 ACL permissions, and I don't think we can map octal permissions to ACLs in a way that will make sense. I think that coming up with different ways to map octal to ACL may make sense for some users, it will likely confuse many more. The current behavior is to return false, telling the user that the stream wrapper is unable to chmod the file. I think that is the appropriate behavior.

For the use case mentioned here, the best way to set an ACL is using stream context options when creating the file.

**Comment by femans** [comment]
Hi Michael, I totally agree that octal permissions don´t map well.
However I don´t have the experience that the current behaviour is returning false, because I simply got a not implemented error, breaking my code, which costed me ample time debugging (which brought me to the idea of implementing it). For a large code base this makes it more complicated to use it as a drop in library, for which I think it was designed; otherwise I could just as well write my own wrapper to do filestuff, (which was my other idea). 
I think it would be more prudent to have it at least available, returning false in some or all cases, or the default acl, or do something useful, maybe depending stream context options. I agree with Jonathan on this, I also like the idea of support for chmod. 
Besides this, the mapping I designed is less confusing than the one in place for mkdir, (no offense, please). Because if you do mkdir('foo/bar', 0700), you don´t expect it to be publicly readable (now it is), but with 0655 you do (now it isn´t). However since S3 doesn´t really work with directories I don´t regard this as a big issue, although I didn´t really test it through.

**Comment by jeskew** [comment]
After spending some time trying to come up with the "right" octal to ACL mapping, I have to say I agree with @mtdowling and I don't think there's any way to do so cleanly. Would it help your use case if `stream_metadata` were implemented and always returned `false`?

**Comment by femans** [comment]
Hi, I think it would be an improvement over a non-implemented. And there is obviously no perfect mapping possible, I agree.
However, for us I don´t see an alternative to either keep using my fork, or creating my own streamwrapper which would be a spinoff of the one in the sdk, because there are too many private methods and variables to be able to simply subclass it. Both options are preferred to changing the aws settings in the code, because I want the codebase to stay filesystem agnostic. In the meanwhile both options are suboptimal, because staying up to date with the official sdk requires merging every time. But that is ok.

**Comment by jeskew** [comment]
@femans Is there a reason why using options set on a stream context wouldn't solve your issue? You stated that you needed to upload items to S3 and have them be publicly readable, which can be accomplished as follows:
```php
$handle = fopen("s3://$bucketName/$key", 'w', null, stream_context_create([
    's3' => ['ACL' => 'public-read'],
]));
fwrite($handle, "I'm publicly visible!");
fclose($handle);
```

Having `chmod` return `false` instead of throwing an error sounds like a better experience, but I would want to be able to accurately model `0642` before adding support for a full-fledged `chmod`. It looks like this wouldn't be possible with canned ACLs.

**Comment by femans** [comment]
As I said, I would like the code to remain as agnostic as possible of the filesystem. This makes it easier to deploy across different types of servers. 
This means using the common operations to do common things, most preferably leaving the code in tact that was there while migrating to s3, and not have a filesystem specific handler; otherwise I have to make a wrapper for this that can switch between different handles for different filesystems. In which case using my own fork is simply easier at this point. 
But I will look into the option of wrapping it in a different way as you suggest. Thanks!

**Comment by jeskew** [comment]
Sure. You might also want to take a look at filesystem abstraction libraries like [Flysystem](http://flysystem.thephpleague.com/) and [Gauffrette](https://github.com/KnpLabs/Gaufrette). Flysystem only supports two levels (completely private or completely public), but it sounds like that would fit your use case.

I'll open a separate PR to have `stream_metadata` always return `false`.

**Comment by femans** [comment]
Thanks Jonathan for the suggestions, and looking into it.

**Pull request closed without merging**
