### PR TITLE
Composer tweaks

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Depends on https://github.com/guzzle/promises/pull/4, https://github.com/guzzle/psr7/pull/5, and https://github.com/guzzle/aws-guzzle-handler/pull/4.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ok, and the dependencies are installable now. :)

**Comment by mtdowling** [comment]
What's the "^" mean?

**Comment by skyzyx** [comment]
> What's the "^" mean?

https://getcomposer.org/doc/01-basic-usage.md#package-versions

> Caret Operator: Very useful for projects that follow semantic versioning. `^1.2.3` is equivalent to `>=1.2.3 <2.0`. For more details, read the next section below.
>
> […]
>
> The `^` operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example `^1.2.3` is equivalent to `>=1.2.3 <2.0.0` as none of the releases until 2.0 should break backwards compatibility. For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`

**Comment by GrahamCampbell** [comment]
@mtdowling Similar to `~`, only follows semantic versioning.

Some examples for you:

* `^0.1` would translate to `0.1.*,>=0.1.0`
* `^0.1.4` would translate to `0.1.*,>=0.1.4`
* `^1.0` would translate to `1.*,>=1.0.0`
* `^1.1` would translate to `1.*,>=1.1.0`
* `^1.4.2` would translate to `1.*,>=1.4.2`

**Comment by hacfi** [comment]
Small correct: according to https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-
it will be
- ^0.1 would translate to `0.1.*,>=0.1.0` **and** `<0.2.0`
- ^0.1.4 would translate to `0.1.*,>=0.1.4` **and** `<0.2.0`

**Comment by GrahamCampbell** [comment]
@hacfi I know - that's why I said "isn't quite how they do it, but i've made it easy to read".

**Comment by hacfi** [comment]
@GrahamCampbell oops..sorry - didn’t read that part :)

**Pull request merged**
