### PR TITLE
Compiled json to php

### PR DESCRIPTION
**Pull request by rquadling**
Whilst working on https://github.com/aws/aws-sdk-php/pull/1370, I ran the `make compile-json` command and it resulted in more compilations that expected. This PR covers the additional compilations.

### CODE REVIEW

**Comment by kstich** [comment]
These occur due to differences in PHP versions for running compile-json in and would be rewritten by our process. Closing.

**Comment by rquadling** [comment]
So should these generated files be excluded from the repo? Maybe built and included in the versioned archive? If I want to work with the source, it would be my responsibility to build via `make compile-json` (and keep them uptodate if I'm playing around with the contents of `data`, but if I use `composer install` or `composer update` (and using dist rather than source), then I'd get them pre-built?

**Comment by kstich** [comment]
That's correct - if you open up the vendor folder when using composer, you'll only see the .json.php files. We include them here in case you wish to build from source.

**Comment by rquadling** [comment]
I'm not sure I explained things fully.

Ideally locally compiling shouldn't result in a diff if they are only build artefacts.

Only the .json files should be in the repo. The .json.php should only be in the distributions. The .json.php should be .gitignored.

Anyway, thanks for looking at this.

**Pull request closed without merging**
