### PR TITLE
Allows Cloudshell to acquire perm from AWS_CONTAINER_CREDENTIALS_FULL…

### PR DESCRIPTION
**Pull request by kuettai**
…_URI

*Issue #, if available:*
https://github.com/aws/aws-sdk-php/issues/2323

*Description of changes:*
Added supports for AWS_CONTAINER_CREDENTIALS_FULL_URI in EcsCredentialProvider.php, this will allows aws-php-sdk to works with CloudShell correctly. Permission in Cloudshell to follow IAM User.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by BenHarris** [comment]
This would also solve issue #2249

**Review by stobrien89 — CHANGES_REQUESTED** [review]
Hi @kuettai,

Thanks for the pull request!  Apologies for the delay.  I think this is something we'd be open to accepting.  Would it be possible for you to rebase and add some unit tests in `EcsCredentialProvider.php` and `CredentialProviderTest.php`?

**Comment by kuettai** [comment]
> Hi @kuettai,
> 
> Thanks for the pull request! Apologies for the delay. I think this is something we'd be open to accepting. Would it be possible for you to rebase and add some unit tests in `EcsCredentialProvider.php` and `CredentialProviderTest.php`?

Acknowledged. Will do later.

**Comment by stobrien89** [comment]
Hi @kuettai,

Closing this one in favor of your new PR.

**Pull request closed without merging**
